  const poster=document.querySelector('#poster');
  document.querySelector('#offset')?.closest('.section')?.remove();
  const collections={
    mao:{name:'毛泽东诗词摘录',meta:'9 条语录 · 阅读意象：跋涉',ghost:'路',seal:'跋<br>涉',quotes:['雄关漫道真如铁\n而今迈步从头越','红军不怕远征难，万水千山只等闲。','世上无难事，只要肯登攀。','为有牺牲多壮志，敢教日月换新天。','待到山花烂漫时，她在丛中笑。','数风流人物，还看今朝。','星星之火，可以燎原。','风物长宜放眼量。','自信人生二百年，会当水击三千里。']},
    sushi:{name:'苏轼词选',meta:'9 条语录 · 阅读意象：月与江',ghost:'月',seal:'江<br>月',quotes:['大江东去，浪淘尽，千古风流人物。','人生如梦，一尊还酹江月。','但愿人长久，千里共婵娟。','回首向来萧瑟处，归去，也无风雨也无晴。','竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。','拣尽寒枝不肯栖，寂寞沙洲冷。','相顾无言，惟有泪千行。','一点浩然气，千里快哉风。','人间有味是清欢。']},
    xin:{name:'辛弃疾词选',meta:'9 条语录 · 阅读意象：剑与长风',ghost:'剑',seal:'长<br>风',quotes:['醉里挑灯看剑，梦回吹角连营。','了却君王天下事，赢得生前身后名。','凭谁问：廉颇老矣，尚能饭否？','我见青山多妩媚，料青山见我应如是。','众里寻他千百度，蓦然回首，那人却在灯火阑珊处。','青山遮不住，毕竟东流去。','天下英雄谁敌手？曹刘。生子当如孙仲谋。','何处望神州？满眼风光北固楼。','最喜小儿无赖，溪头卧剥莲蓬。']}
  };
  const collectionSection=document.createElement('section');collectionSection.className='section';collectionSection.innerHTML='<div class="section-title">诗词版本</div><div class="choices"><button class="choice active" data-collection="mao">毛泽东诗词<span>跋涉、意志与开阔</span></button><button class="choice" data-collection="sushi">苏轼词选<span>江月、旷达与清欢</span></button><button class="choice" data-collection="xin">辛弃疾词选<span>剑与长风、壮志与苍凉</span></button></div>';document.querySelector('.right h2').after(collectionSection);
  const languageSection=document.createElement('section');languageSection.className='section';languageSection.innerHTML='<div class="section-title">字形</div><div class="choices density-choices"><button class="choice active" data-language="simplified">简体</button><button class="choice" data-language="traditional">繁體</button></div>';collectionSection.after(languageSection);
  const currentWorkSection=document.createElement('section');currentWorkSection.className='section';currentWorkSection.hidden=true;currentWorkSection.innerHTML='<div class="section-title">当前作品</div><div class="current-work"><span id="currentWorkName"></span><button id="reselectWork">重新选择诗词</button></div>';languageSection.before(currentWorkSection);
  const quoteEditSection=document.createElement('section');quoteEditSection.className='section';quoteEditSection.hidden=true;quoteEditSection.innerHTML='<div class="section-title">句子微调</div><div class="sentence-editor"><div class="selected-copy" id="selectedQuoteCopy">点击卡片中的一句诗</div><div class="micro-tools"><button id="moveQuoteUp" title="与上一句交换">↑</button><button id="moveQuoteDown" title="与下一句交换">↓</button><button id="finishQuoteEdit">完成</button><button id="undoQuoteEdit" disabled>撤销</button><button id="resetQuoteEdits">恢复默认</button></div><div class="micro-tools" id="toneTools"><button data-quote-tone="white"><i class="tone-dot" style="background:#f2eee4"></i>白色</button><button data-quote-tone="lightgreen"><i class="tone-dot" style="background:#a9c7b1"></i>浅绿</button><button data-quote-tone="deepgreen"><i class="tone-dot" style="background:#34594b"></i>深绿</button><button data-quote-tone="lightgray"><i class="tone-dot" style="background:#b8b9b5"></i>浅灰</button><button data-quote-tone="black"><i class="tone-dot" style="background:#191b1b"></i>深黑</button></div><div class="micro-tools" id="weightTools"><button data-quote-weight="normal" class="active">常规</button><button data-quote-weight="bold">加粗</button></div><div class="micro-tools" id="sizeTools"><button data-quote-scale="0.86">紧凑</button><button data-quote-scale="1" class="active">标准</button><button data-quote-scale="1.16">强调</button></div><div class="sentence-help">位置使用网格槽位交换，系统会继续检查文字溢出。编辑会自动保存在当前浏览器。</div></div>';currentWorkSection.after(quoteEditSection);
  const formatSection=document.createElement('section');formatSection.className='section';formatSection.dataset.mobilePanel='layout';formatSection.innerHTML='<div class="section-title">画幅</div><div class="choices format-tools"><button class="choice active" data-format="social">3:4<span>社交分享</span></button><button class="choice" data-format="a4">A4<span>打印比例</span></button></div><div class="micro-tools" style="margin-top:8px"><button id="toggleSafeGuide">显示安全边距</button></div>';quoteEditSection.after(formatSection);
  const restoreLastButton=document.createElement('button');restoreLastButton.className='example';restoreLastButton.id='restoreLastWork';restoreLastButton.textContent='恢复上次作品';restoreLastButton.hidden=true;document.querySelector('.examples').appendChild(restoreLastButton);
  currentWorkSection.querySelector('#reselectWork').onclick=()=>{discovery.hidden=false;chooseView.hidden=true;searchView.hidden=false};
  document.querySelector('button[data-style="rupture"]')?.remove();
  const traditionalMap={'泽':'澤','东':'東','诗':'詩','词':'詞','录':'錄','条':'條','语':'語','阅':'閱','读':'讀','意':'意','象':'象','跋':'跋','涉':'涉','关':'關','漫':'漫','道':'道','真':'真','如':'如','铁':'鐵','迈':'邁','步':'步','头':'頭','红':'紅','军':'軍','远':'遠','征':'征','难':'難','万':'萬','千':'千','山':'山','闲':'閒','世':'世','无':'無','事':'事','只':'只','要':'要','肯':'肯','登':'登','攀':'攀','为':'為','牺':'犧','牲':'牲','多':'多','壮':'壯','志':'志','敢':'敢','教':'教','日':'日','月':'月','换':'換','新':'新','天':'天','时':'時','她':'她','丛':'叢','风':'風','流':'流','还':'還','今':'今','朝':'朝','星':'星','火':'火','可':'可','以':'以','燎':'燎','原':'原','物':'物','长':'長','宜':'宜','放':'放','眼':'眼','量':'量','自':'自','信':'信','百':'百','年':'年','会':'會','当':'當','水':'水','击':'擊','里':'裡','苏':'蘇','轼':'軾','选':'選','与':'與','江':'江','大':'大','去':'去','浪':'浪','淘':'淘','尽':'盡','古':'古','人':'人','梦':'夢','尊':'尊','酹':'酹','但':'但','愿':'願','久':'久','共':'共','婵':'嬋','娟':'娟','回':'回','首':'首','向':'向','来':'來','萧':'蕭','瑟':'瑟','处':'處','归':'歸','也':'也','雨':'雨','晴':'晴','竹':'竹','杖':'杖','芒':'芒','鞋':'鞋','轻':'輕','胜':'勝','马':'馬','谁':'誰','怕':'怕','蓑':'蓑','任':'任','平':'平','生':'生','拣':'揀','寒':'寒','枝':'枝','不':'不','栖':'棲','寂':'寂','寞':'寞','洲':'洲','冷':'冷','相':'相','顾':'顧','言':'言','惟':'惟','有':'有','泪':'淚','行':'行','点':'點','浩':'浩','然':'然','气':'氣','快':'快','哉':'哉','间':'間','味':'味','清':'清','欢':'歡','辛':'辛','弃':'棄','疾':'疾','剑':'劍','灯':'燈','看':'看','吹':'吹','角':'角','连':'連','营':'營','了':'了','却':'卻','君':'君','王':'王','下':'下','赢':'贏','得':'得','前':'前','后':'後','名':'名','凭':'憑','问':'問','颇':'頗','老':'老','矣':'矣','尚':'尚','能':'能','饭':'飯','否':'否','见':'見','青':'青','妩':'嫵','媚':'媚','料':'料','应':'應','是':'是','众':'眾','寻':'尋','他':'他','度':'度','蓦':'驀','那':'那','阑':'闌','珊':'珊','遮':'遮','毕':'畢','竟':'竟','英':'英','雄':'雄','敌':'敵','手':'手','曹':'曹','刘':'劉','孙':'孫','仲':'仲','谋':'謀','何':'何','望':'望','神':'神','州':'州','满':'滿','光':'光','北':'北','固':'固','楼':'樓','最':'最','喜':'喜','儿':'兒','赖':'賴','溪':'溪','卧':'臥','剥':'剝','莲':'蓮','蓬':'蓬','余':'餘','音':'音'};
  const toTraditional=text=>[...text].map(char=>traditionalMap[char]||char).join('');
  let activeCollection='mao',activeLanguage='simplified';
  const localize=text=>activeLanguage==='traditional'?toTraditional(text):text;
  function scheduleFit(){requestAnimationFrame(()=>requestAnimationFrame(fitQuotes))}
  function fitQuotes(){poster.querySelectorAll('.quote').forEach(quote=>{quote.style.removeProperty('font-size')});poster.querySelectorAll('.quote').forEach(quote=>{if(quote.offsetParent===null)return;let size=parseFloat(getComputedStyle(quote).fontSize)*Number(quote.dataset.scale||1);quote.style.setProperty('font-size',`${size}px`,'important');while((quote.scrollWidth>quote.clientWidth+1||quote.scrollHeight>quote.clientHeight+1)&&size>11){size-=1;quote.style.setProperty('font-size',`${size}px`,'important')}})}
  function applyQuoteLimit(){const item=collections[activeCollection];const limit=poster.dataset.style==='glyphfield'?9:7;poster.querySelectorAll('.quote').forEach((quote,index)=>{quote.hidden=index>=limit||!item.quotes[index]})}
  function setCollection(key){activeCollection=key;const item=collections[key];poster.querySelectorAll('.quote').forEach((quote,index)=>{const text=item.quotes[index];quote.hidden=!text;if(text)quote.innerHTML=localize(text).replace('\n','<br>');else quote.textContent=''});applyQuoteLimit();poster.querySelector('.ghost').textContent=localize(item.ghost);poster.querySelector('.seal').innerHTML=localize(item.seal);poster.querySelector('.edition').textContent=`${localize(item.name)} / ${localize('余音')} 2026`;document.querySelector('#sourceTitle').textContent=localize(item.name);document.querySelector('#sourceMeta').textContent=localize(item.meta);document.querySelector('.badge').textContent=localize(item.name);scheduleFit()}
  document.querySelectorAll('[data-collection]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-collection]').forEach(item=>item.classList.remove('active'));button.classList.add('active');setCollection(button.dataset.collection)});
  document.querySelectorAll('[data-language]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-language]').forEach(item=>item.classList.remove('active'));button.classList.add('active');activeLanguage=button.dataset.language;setCollection(activeCollection)});
  poster.dataset.density='balanced';
  const quoteTexts=['待到山花烂漫时，她在丛中笑。','数风流人物，还看今朝。','星星之火，可以燎原。','风物长宜放眼量。','自信人生二百年，会当水击三千里。'];
  poster.querySelector('.q5').textContent=quoteTexts[0];
  quoteTexts.slice(1).forEach((text,index)=>{const quote=document.createElement('div');quote.className=`quote q${index+6}`;quote.textContent=text;poster.querySelector('.edition').before(quote)});
  const quoteGrid=document.createElement('div');quoteGrid.className='quote-grid';poster.querySelectorAll('.quote').forEach(quote=>quoteGrid.appendChild(quote));poster.prepend(quoteGrid);
  const DRAFT_KEY='yuyin:last-card:v1',HISTORY_KEY='yuyin:works:v1';let selectedQuoteIndex=-1,customDefaultQuotes=[],editHistory=[],currentWorkId='';
  const quoteNodes=()=>[...poster.querySelectorAll('.quote')];
  function makeWorkId(){return globalThis.crypto?.randomUUID?.()||`work-${Date.now()}-${Math.random().toString(36).slice(2)}`}
  function readHistory(){try{const value=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(value)?value:[]}catch(error){return[]}}
  function captureDraft(){return activeCollection==='custom'?{id:currentWorkId||makeWorkId(),updatedAt:Date.now(),collection:{...collections.custom,quotes:[...collections.custom.quotes]},defaultQuotes:[...customDefaultQuotes],styles:quoteNodes().map(quote=>({tone:quote.dataset.tone||'',scale:quote.dataset.scale||'',weight:quote.dataset.weight||''})),posterStyle:poster.dataset.style,theme:poster.dataset.theme||'',composition:poster.dataset.composition||'a',format:poster.dataset.format||'social',safeGuide:poster.dataset.safeGuide==='true',language:activeLanguage,workName:currentWorkSection.querySelector('#currentWorkName').textContent}:null}
  function saveDraft(){const draft=captureDraft();if(!draft)return;currentWorkId=draft.id;try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));const history=readHistory().filter(item=>item.id!==draft.id);history.unshift(draft);localStorage.setItem(HISTORY_KEY,JSON.stringify(history.slice(0,10)));restoreLastButton.hidden=false;renderHistory()}catch(error){console.warn('Draft save unavailable',error)}}
  function pushHistory(){const snapshot=captureDraft();if(!snapshot)return;editHistory.push(snapshot);if(editHistory.length>20)editHistory.shift();document.querySelector('#undoQuoteEdit').disabled=false}
  function applyDraft(draft){if(!draft?.collection?.quotes?.length)return;currentWorkId=draft.id||makeWorkId();collections.custom={...draft.collection,quotes:[...draft.collection.quotes]};customDefaultQuotes=[...(draft.defaultQuotes||draft.collection.quotes)];activeLanguage=draft.language||'simplified';poster.dataset.style=draft.posterStyle||'editorial';poster.dataset.theme=draft.theme||'';poster.dataset.composition=draft.composition||'a';poster.dataset.format=draft.format||'social';poster.dataset.safeGuide=String(Boolean(draft.safeGuide));setCollection('custom');quoteNodes().forEach((quote,index)=>{const style=draft.styles?.[index]||{};if(style.tone)quote.dataset.tone=style.tone;else delete quote.dataset.tone;if(style.scale)quote.dataset.scale=style.scale;else delete quote.dataset.scale;if(style.weight)quote.dataset.weight=style.weight;else delete quote.dataset.weight});document.querySelectorAll('button[data-style]').forEach(button=>button.classList.toggle('active',button.dataset.style===poster.dataset.style));document.querySelectorAll('[data-theme]').forEach(button=>button.classList.toggle('active',(button.dataset.theme==='paper'?'':button.dataset.theme)===poster.dataset.theme));document.querySelectorAll('[data-language]').forEach(button=>button.classList.toggle('active',button.dataset.language===activeLanguage));document.querySelectorAll('button[data-format]').forEach(button=>button.classList.toggle('active',button.dataset.format===poster.dataset.format));document.querySelector('#toggleSafeGuide').textContent=poster.dataset.safeGuide==='true'?'隐藏安全边距':'显示安全边距';const s=styles[poster.dataset.style];if(s){styleTitle.textContent=s[0];styleSub.textContent=s[1];rule.textContent=s[2]}regenerateBtn.textContent=poster.dataset.composition==='b'?'换个构图 · B':'换个构图 · A';collectionSection.hidden=true;currentWorkSection.hidden=false;quoteEditSection.hidden=false;currentWorkSection.querySelector('#currentWorkName').textContent=draft.workName||collections.custom.name;selectedQuoteIndex=-1;discovery.hidden=true;refreshQuoteEditor();scheduleFit()}
  function renderHistory(){const section=document.querySelector('#workHistory'),list=document.querySelector('#historyList'),history=readHistory();section.hidden=!history.length;list.innerHTML=history.map(item=>{const date=new Date(item.updatedAt||0).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});const template=styles[item.posterStyle]?.[0]||'阅读卡';return `<div class="history-item"><div><div class="history-name">${escapeHtml(item.workName||item.collection?.name||'未命名作品')}</div><div class="history-meta">${escapeHtml(template)} · ${escapeHtml(date)}</div></div><div class="history-actions"><button data-open-work="${escapeHtml(item.id)}">打开</button><button data-delete-work="${escapeHtml(item.id)}">删除</button></div></div>`}).join('');list.querySelectorAll('[data-open-work]').forEach(button=>button.onclick=()=>{const draft=readHistory().find(item=>item.id===button.dataset.openWork);if(draft){applyDraft(draft);editHistory=[];document.querySelector('#undoQuoteEdit').disabled=true}});list.querySelectorAll('[data-delete-work]').forEach(button=>button.onclick=()=>{const history=readHistory().filter(item=>item.id!==button.dataset.deleteWork);localStorage.setItem(HISTORY_KEY,JSON.stringify(history));try{const latest=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(latest?.id===button.dataset.deleteWork){localStorage.removeItem(DRAFT_KEY);restoreLastButton.hidden=true}}catch(error){}renderHistory()})}
  function visibleQuoteLimit(){return Math.min(collections[activeCollection]?.quotes.length||0,poster.dataset.style==='glyphfield'?9:7)}
  function refreshQuoteEditor(){const nodes=quoteNodes();nodes.forEach((node,index)=>node.classList.toggle('is-selected',index===selectedQuoteIndex));const selected=nodes[selectedQuoteIndex];document.querySelector('#selectedQuoteCopy').textContent=selected?selected.textContent:'点击卡片中的一句诗';document.querySelector('#moveQuoteUp').disabled=selectedQuoteIndex<=0;document.querySelector('#moveQuoteDown').disabled=selectedQuoteIndex<0||selectedQuoteIndex>=visibleQuoteLimit()-1;document.querySelector('#finishQuoteEdit').disabled=!selected;document.querySelectorAll('[data-quote-tone]').forEach(button=>button.classList.toggle('active',button.dataset.quoteTone===selected?.dataset.tone));document.querySelectorAll('[data-quote-weight]').forEach(button=>button.classList.toggle('active',button.dataset.quoteWeight===(selected?.dataset.weight||'normal')));document.querySelectorAll('[data-quote-scale]').forEach(button=>button.classList.toggle('active',Number(button.dataset.quoteScale)===Number(selected?.dataset.scale||1)))}
  function selectQuote(index){if(activeCollection!=='custom'||index>=visibleQuoteLimit())return;selectedQuoteIndex=index;if(matchMedia('(max-width:700px)').matches){rightPanel.dataset.mobileTab='sentence';mobileTabs.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.mobileTarget==='sentence'))}refreshQuoteEditor()}
  poster.addEventListener('click',event=>{const quote=event.target.closest('.quote');if(quote)selectQuote(quoteNodes().indexOf(quote));else{selectedQuoteIndex=-1;refreshQuoteEditor()}});
  function moveSelectedQuote(direction){const next=selectedQuoteIndex+direction;if(selectedQuoteIndex<0||next<0||next>=visibleQuoteLimit())return;pushHistory();const quotes=collections.custom.quotes;[quotes[selectedQuoteIndex],quotes[next]]=[quotes[next],quotes[selectedQuoteIndex]];const nodes=quoteNodes();const tone=nodes[selectedQuoteIndex].dataset.tone,scale=nodes[selectedQuoteIndex].dataset.scale,weight=nodes[selectedQuoteIndex].dataset.weight;nodes[selectedQuoteIndex].dataset.tone=nodes[next].dataset.tone||'';nodes[selectedQuoteIndex].dataset.scale=nodes[next].dataset.scale||'';nodes[selectedQuoteIndex].dataset.weight=nodes[next].dataset.weight||'';nodes[next].dataset.tone=tone||'';nodes[next].dataset.scale=scale||'';nodes[next].dataset.weight=weight||'';selectedQuoteIndex=next;setCollection('custom');refreshQuoteEditor();saveDraft()}
  document.querySelector('#moveQuoteUp').onclick=()=>moveSelectedQuote(-1);document.querySelector('#moveQuoteDown').onclick=()=>moveSelectedQuote(1);
  document.querySelector('#finishQuoteEdit').onclick=()=>{selectedQuoteIndex=-1;refreshQuoteEditor()};
  document.querySelectorAll('[data-quote-tone]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();const tone=button.dataset.quoteTone;if(tone==='default')delete quote.dataset.tone;else quote.dataset.tone=tone;refreshQuoteEditor();saveDraft()});
  document.querySelectorAll('[data-quote-scale]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();quote.dataset.scale=button.dataset.quoteScale;scheduleFit();refreshQuoteEditor();saveDraft()});
  document.querySelectorAll('[data-quote-weight]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();const weight=button.dataset.quoteWeight;if(weight==='normal')delete quote.dataset.weight;else quote.dataset.weight=weight;scheduleFit();refreshQuoteEditor();saveDraft()});
  document.querySelector('#undoQuoteEdit').onclick=()=>{const draft=editHistory.pop();if(!draft)return;applyDraft(draft);document.querySelector('#undoQuoteEdit').disabled=editHistory.length===0;saveDraft()};
  document.querySelector('#resetQuoteEdits').onclick=()=>{if(activeCollection!=='custom')return;pushHistory();collections.custom.quotes=[...customDefaultQuotes];quoteNodes().forEach(quote=>{delete quote.dataset.tone;delete quote.dataset.scale;delete quote.dataset.weight});selectedQuoteIndex=-1;setCollection('custom');refreshQuoteEditor();saveDraft()};
  poster.querySelector('.edition').textContent='毛泽东诗词摘录 / 余音 2026';
  const paperSection=[...document.querySelectorAll('.section')].find(section=>section.textContent.includes('纸墨'));
  poster.dataset.density='balanced';
  const styles={editorial:['编辑留白','模块网格 · 单一视觉焦点','理性网格与克制留白，适合强调一句核心文本。'],songbook:['宋刻手卷','版心界栏 · 连续展开 · 纵向行气','把宋刻书页的界栏秩序与手卷的连续阅读合为一体。'],modern:['现代构成','几何分区 · 黑红对照 · 无衬线碰撞','用现代编辑网格重组古典文本，保留强烈而清晰的层级。'],letterpress:['活字套印','双色油墨 · 压印边缘 · 模块字块','模拟活字与双色套印，强调材料感和文字块重量。'],night:['夜读笺','深纸 · 金墨 · 静谧低对比','以低照度、细线和微金色构成适合夜读的静谧卡面。'],impression:['印象拼贴','后现代色块 · 半透明叠印 · 不稳定边界','用印象派的色面与后现代拼贴重组句子，保持可读的失衡。'],glyphfield:['字阵残章','横竖混排 · 多色簇 · 高密度','以散落字阵、横竖行气与多色层级构成高密度的视觉拼贴。']};
  const templateChoices=document.querySelector('button[data-style]').closest('.choices');templateChoices.classList.add('template-choices');templateChoices.innerHTML=Object.entries(styles).map(([key,value],index)=>`<button class="choice ${index===0?'active':''}" data-style="${key}">${value[0]}<span>${value[1]}</span></button>`).join('');
  const rightPanel=document.querySelector('.right'),mobileTabs=document.createElement('div');mobileTabs.className='mobile-editor-tabs';mobileTabs.innerHTML='<button class="active" data-mobile-target="layout">版式</button><button data-mobile-target="sentence">句子</button><button data-mobile-target="paper">纸墨</button>';rightPanel.querySelector('h2').after(mobileTabs);rightPanel.dataset.mobileTab='layout';templateChoices.closest('.section').dataset.mobilePanel='layout';quoteEditSection.dataset.mobilePanel='sentence';languageSection.dataset.mobilePanel='paper';paperSection.dataset.mobilePanel='paper';[...rightPanel.querySelectorAll('.section')].filter(section=>!section.dataset.mobilePanel&&section!==currentWorkSection&&section!==collectionSection).forEach(section=>section.dataset.mobilePanel='layout');mobileTabs.querySelectorAll('button').forEach(button=>button.onclick=()=>{mobileTabs.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');rightPanel.dataset.mobileTab=button.dataset.mobileTarget});
  document.querySelectorAll('button[data-style]').forEach(b=>b.onclick=()=>{if(activeCollection==='custom')pushHistory();document.querySelectorAll('button[data-style]').forEach(x=>x.classList.remove('active'));b.classList.add('active');poster.dataset.style=b.dataset.style;applyQuoteLimit();if(selectedQuoteIndex>=visibleQuoteLimit())selectedQuoteIndex=-1;refreshQuoteEditor();const s=styles[b.dataset.style];styleTitle.textContent=s[0];styleSub.textContent=s[1];rule.textContent=s[2];scheduleFit();saveDraft()});
  document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{if(activeCollection==='custom')pushHistory();document.querySelectorAll('[data-theme]').forEach(x=>x.classList.remove('active'));b.classList.add('active');poster.dataset.theme=b.dataset.theme==='paper'?'':b.dataset.theme;scheduleFit();saveDraft()});
  document.querySelectorAll('button[data-format]').forEach(button=>button.onclick=()=>{if(activeCollection==='custom')pushHistory();document.querySelectorAll('button[data-format]').forEach(item=>item.classList.remove('active'));button.classList.add('active');poster.dataset.format=button.dataset.format;scheduleFit();saveDraft()});
  document.querySelector('#toggleSafeGuide').onclick=()=>{if(activeCollection==='custom')pushHistory();const visible=poster.dataset.safeGuide!=='true';poster.dataset.safeGuide=String(visible);document.querySelector('#toggleSafeGuide').textContent=visible?'隐藏安全边距':'显示安全边距';saveDraft()};
  poster.dataset.composition='a';regenerateBtn.onclick=()=>{if(activeCollection==='custom')pushHistory();const useB=poster.dataset.composition!=='b';poster.dataset.composition=useB?'b':'a';regenerateBtn.textContent=useB?'换个构图 · B':'换个构图 · A';scheduleFit();saveDraft()};
  printBtn.onclick=()=>{selectedQuoteIndex=-1;refreshQuoteEditor();document.body.classList.add('preview-mode')};
  previewExit.onclick=()=>document.body.classList.remove('preview-mode');
  document.addEventListener('keydown',event=>{if(event.key==='Escape')document.body.classList.remove('preview-mode')});
  document.fonts?.ready.then(scheduleFit);scheduleFit();

  const discovery=document.querySelector('#discovery');
  const searchView=document.querySelector('#searchView');
  const chooseView=document.querySelector('#chooseView');
  const searchResults=document.querySelector('#searchResults');
  const poetryQuery=document.querySelector('#poetryQuery');
  const searchBtn=document.querySelector('#searchBtn');
  let currentCandidates=[];

  const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function renderCandidates(candidates,mode,requestedAuthor){
    currentCandidates=candidates;
    if(!candidates.length){searchResults.innerHTML=`${requestedAuthor?`<div class="intent-lock">当前限定作者：${escapeHtml(requestedAuthor)}</div>`:''}<div class="search-state">没有找到可靠候选。系统不会用其他作者的作品代替，请换一种描述或稍后重试。</div>`;return}
    const selected=new Set();
    const updateBar=()=>{
      const count=selected.size;
      const barSpan=searchResults.querySelector('.multi-select-bar span');
      const barBtn=searchResults.querySelector('.multi-select-bar button');
      if(barSpan)barSpan.textContent=count?`已选择 ${count} 篇`:'请至少选择一篇诗词';
      if(barBtn)barBtn.disabled=count===0;
    };
    const doCurate=async()=>{
      if(!selected.size)return;
      const works=[...selected].map(i=>currentCandidates[i]);
      chooseView.innerHTML='<div class="search-state">正在从所选诗词中策展句子……</div>';
      searchView.hidden=true;chooseView.hidden=false;
      try{
        const result=await window.YuyinApi.curatePoetry(works.map(w=>({author:w.author,title:w.title,lines:w.lines})));
        showCurateView(result.quotes||[],result.themeChar||'诗',result.mode||'demo',works);
      }catch(error){
        chooseView.innerHTML=`<div class="search-state">${escapeHtml(error.message)}</div>`;
      }
    };
    searchResults.innerHTML=`${requestedAuthor?`<div class="intent-lock">当前限定作者：${escapeHtml(requestedAuthor)}，其他作者的候选会被自动过滤。</div>`:''}<div class="result-head"><h3>勾选作品</h3><span>${mode==='demo'?'演示数据 · 配置 DeepSeek 后启用实时搜索':'AI 候选 · 原文请在发布前核验'}</span></div><div class="candidate-grid">${candidates.map((item,index)=>`<label class="candidate" data-candidate="${index}"><input type="checkbox" class="candidate-check" value="${index}">${item.sourceStatus==='model-unverified'?'<span class="unverified-badge">⚠ AI 候选 · 原文待核验</span>':''}<small>${escapeHtml(item.dynasty)} · ${escapeHtml(item.author)} · ${escapeHtml(item.genre||'诗词')}</small><h4>${escapeHtml(item.title)}</h4><p>${escapeHtml(item.reason)}</p><div class="line-preview">${escapeHtml(item.lines[0]||'')}</div></label>`).join('')}</div><div class="multi-select-bar"><span>请至少选择一篇作品</span><button disabled id="curateBtn">AI 策展选句</button></div>`;
    searchResults.querySelectorAll('.candidate input[type="checkbox"]').forEach(cb=>{
      cb.onchange=()=>{
        const index=Number(cb.value);
        cb.checked?selected.add(index):selected.delete(index);
        cb.closest('.candidate').classList.toggle('selected',cb.checked);
        updateBar();
      };
    });
    searchResults.querySelector('#curateBtn').onclick=doCurate;
    searchResults.querySelectorAll('.candidate').forEach(label=>{
      label.addEventListener('click',function(e){if(e.target.tagName==='INPUT')return;const cb=this.querySelector('input[type="checkbox"]');cb.checked=!cb.checked;cb.dispatchEvent(new Event('change'))});
    });
  }
  function showCurateView(quotes,themeChar,mode,works){
    const authorNames=[...new Set(works.map(w=>w.author))].join('·');
    const workNames=works.map(w=>`《${w.title}》`).join('、');
    chooseView.innerHTML=`<div class="chooser"><aside><button class="example" id="backToResults">← 返回候选</button><h3>${escapeHtml(authorNames)}</h3><div class="chooser-meta">${escapeHtml(workNames)}<br><br>${mode==='demo'?'演示策展':'AI 策展 · 原文请在发布前核验'}<br>共 ${quotes.length} 句</div></aside><div><div class="result-head"><h3>AI 策展结果</h3><span>可编辑后生成卡片</span></div><div class="curate-rule">普通模板展示前 7 句；“字阵残章”最多展示 9 句。切换模板不会删除句子。</div><div class="curate-list">${quotes.map((item,index)=>`<div class="curate-quote"><textarea data-index="${index}" readOnly>${escapeHtml(item.text)}</textarea><div class="curate-source">—— ${escapeHtml(item.source)}${index>=7?' · 仅字阵残章展示':''}</div></div>`).join('')}</div><div class="curate-actions"><button id="editCurated">编辑原文</button><button class="confirm" id="createCuratedCard">生成阅读卡</button></div></div></div>`;
    chooseView.querySelector('#backToResults').onclick=()=>{chooseView.hidden=true;searchView.hidden=false};
    chooseView.querySelector('#editCurated').onclick=()=>{const tas=chooseView.querySelectorAll('.curate-quote textarea');const toggling=!tas[0]?.readOnly;tas.forEach(t=>t.readOnly=toggling)};
    chooseView.querySelector('#createCuratedCard').onclick=()=>{
      const edited=[...chooseView.querySelectorAll('.curate-quote textarea')].map(t=>t.value.trim()).filter(Boolean);
      if(!edited.length){alert('请至少保留一句');return}
      const limited=edited.slice(0,9);
      currentWorkId=makeWorkId();collections.custom={
        name:`${authorNames} 诗选`,
        meta:`${limited.length} 条语录 · AI 策展`,
        ghost:themeChar,
        seal:themeChar.slice(0,2).split('').join('<br>'),
        quotes:limited
      };
      customDefaultQuotes=[...limited];selectedQuoteIndex=-1;quoteNodes().forEach(quote=>{delete quote.dataset.tone;delete quote.dataset.scale;delete quote.dataset.weight});quoteEditSection.hidden=false;
      poster.dataset.density=limited.length>7?'dense':limited.length>5?'balanced':'loose';
      setCollection('custom');collectionSection.hidden=true;currentWorkSection.hidden=false;
      currentWorkSection.querySelector('#currentWorkName').textContent=`${authorNames} · ${workNames}`;
      editHistory=[];document.querySelector('#undoQuoteEdit').disabled=true;discovery.hidden=true;saveDraft();
    };
  }
  async function runSearch(query){
    searchBtn.disabled=true;searchResults.innerHTML='<div class="search-state">正在寻找诗词与作品……</div>';
    try{const result=await window.YuyinApi.searchPoetry(query);renderCandidates(result.candidates||[],result.mode,result.requestedAuthor)}catch(error){searchResults.innerHTML=`<div class="search-state">${escapeHtml(error.message)}。请确认使用 Node 服务启动，而不是直接打开 HTML。<br><button class="example" onclick="runSearch(poetryQuery.value.trim())">重新尝试</button></div>`}finally{searchBtn.disabled=false}
  }
  document.querySelector('#poetrySearch').onsubmit=event=>{event.preventDefault();const query=poetryQuery.value.trim();if(query.length>=2)runSearch(query)};
  document.querySelectorAll('.example').forEach(button=>button.onclick=()=>{poetryQuery.value=button.textContent;runSearch(button.textContent)});
  restoreLastButton.onclick=()=>{try{applyDraft(JSON.parse(localStorage.getItem(DRAFT_KEY)||'null'));editHistory=[];document.querySelector('#undoQuoteEdit').disabled=true}catch(error){localStorage.removeItem(DRAFT_KEY);restoreLastButton.hidden=true}};
  try{restoreLastButton.hidden=!localStorage.getItem(DRAFT_KEY)}catch(error){restoreLastButton.hidden=true}
  try{const previous=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(previous?.collection?.quotes?.length&&!readHistory().length){previous.id=previous.id||makeWorkId();previous.updatedAt=previous.updatedAt||Date.now();localStorage.setItem(DRAFT_KEY,JSON.stringify(previous));localStorage.setItem(HISTORY_KEY,JSON.stringify([previous]))}}catch(error){}
  renderHistory();
  const searchPanel=document.querySelector('.search-panel'),lyricEntry=document.querySelector('#lyricEntry'),lyricText=document.querySelector('#lyricText'),lyricConsent=document.querySelector('#lyricConsent'),lyricCandidates=document.querySelector('#lyricCandidates'),extractLyricLines=document.querySelector('#extractLyricLines'),createLyricCard=document.querySelector('#createLyricCard');
  function sourceLyricLines(){const seen=new Set();return lyricText.value.split(/\r?\n/).map(line=>line.trim()).filter(line=>{if(!line||seen.has(line))return false;seen.add(line);return true})}
  function selectedLyricLines(){return [...lyricCandidates.querySelectorAll('input:checked')].map(input=>input.value)}
  function refreshLyricSelection(){const count=selectedLyricLines().length;document.querySelector('#lyricCount').textContent=`已选择 ${count} 句 · 请选择 4-9 句`;createLyricCard.disabled=count<4||count>9;lyricCandidates.querySelectorAll('input:not(:checked)').forEach(input=>input.disabled=count>=9)}
  function resetLyricCandidates(){lyricCandidates.hidden=true;lyricCandidates.innerHTML='';createLyricCard.hidden=true;const count=sourceLyricLines().length;document.querySelector('#lyricCount').textContent=`${count} 行 · ${count<4?'至少需要 4 行':'可以让 AI 提取候选'}`;extractLyricLines.hidden=false;extractLyricLines.disabled=count<4||!lyricConsent.checked}
  document.querySelector('#openLyricEntry').onclick=()=>{searchPanel.hidden=true;searchResults.hidden=true;document.querySelector('#workHistory').hidden=true;lyricEntry.hidden=false;resetLyricCandidates()};
  document.querySelector('#closeLyricEntry').onclick=()=>{lyricEntry.hidden=true;searchPanel.hidden=false;searchResults.hidden=false;renderHistory()};
  lyricText.oninput=resetLyricCandidates;lyricConsent.onchange=resetLyricCandidates;
  extractLyricLines.onclick=async()=>{const source=sourceLyricLines();if(source.length<4||!lyricConsent.checked)return;extractLyricLines.disabled=true;extractLyricLines.textContent='正在提取…';try{const result=await window.YuyinApi.extractLyrics(source.join('\n'));const candidates=result.candidates||[];lyricCandidates.innerHTML=candidates.map((line,index)=>`<label class="lyric-option"><input type="checkbox" value="${escapeHtml(line)}" ${index<Math.min(7,candidates.length)?'checked':''}><span>${escapeHtml(line)}</span></label>`).join('');lyricCandidates.hidden=false;extractLyricLines.hidden=true;createLyricCard.hidden=false;lyricCandidates.querySelectorAll('input').forEach(input=>input.onchange=refreshLyricSelection);refreshLyricSelection()}catch(error){document.querySelector('#lyricCount').textContent=error.message;extractLyricLines.disabled=false}finally{extractLyricLines.textContent='AI提取候选句'}};
  createLyricCard.onclick=()=>{const lines=selectedLyricLines();if(lines.length<4||lines.length>9||!lyricConsent.checked)return;const title=document.querySelector('#lyricTitle').value.trim()||'未命名歌词';const author=document.querySelector('#lyricAuthor').value.trim()||'佚名';const themeChar=(lines.join('').match(/[\u3400-\u9fff]/)||['词'])[0];currentWorkId=makeWorkId();collections.custom={name:`${title} · ${author}`,meta:`${lines.length} 条歌词摘录 · 用户选择`,ghost:themeChar,seal:themeChar,quotes:lines};customDefaultQuotes=[...lines];selectedQuoteIndex=-1;quoteNodes().forEach(quote=>{delete quote.dataset.tone;delete quote.dataset.scale;delete quote.dataset.weight});poster.dataset.density=lines.length>7?'dense':lines.length>5?'balanced':'loose';setCollection('custom');collectionSection.hidden=true;currentWorkSection.hidden=false;quoteEditSection.hidden=false;currentWorkSection.querySelector('#currentWorkName').textContent=`${title} · ${author}`;editHistory=[];document.querySelector('#undoQuoteEdit').disabled=true;discovery.hidden=true;saveDraft()};
