  function visibleQuoteLimit(){return Math.min(collections[activeCollection]?.quotes.length||0,poster.dataset.style==='glyphfield'?9:7)}
  function refreshQuoteEditor(){const nodes=quoteNodes();nodes.forEach((node,index)=>node.classList.toggle('is-selected',index===selectedQuoteIndex));const selected=nodes[selectedQuoteIndex];document.querySelector('#selectedQuoteCopy').textContent=selected?selected.textContent:'点击卡片中的一句诗';document.querySelector('#moveQuoteUp').disabled=selectedQuoteIndex<=0;document.querySelector('#moveQuoteDown').disabled=selectedQuoteIndex<0||selectedQuoteIndex>=visibleQuoteLimit()-1;document.querySelector('#finishQuoteEdit').disabled=!selected;document.querySelectorAll('[data-quote-tone]').forEach(button=>button.classList.toggle('active',button.dataset.quoteTone===selected?.dataset.tone));document.querySelectorAll('[data-quote-weight]').forEach(button=>button.classList.toggle('active',button.dataset.quoteWeight===(selected?.dataset.weight||'normal')));document.querySelectorAll('[data-quote-scale]').forEach(button=>button.classList.toggle('active',Number(button.dataset.quoteScale)===Number(selected?.dataset.scale||1)))}
  function selectQuote(index){if(activeCollection!=='custom'||index>=visibleQuoteLimit())return;selectedQuoteIndex=index;if(matchMedia('(max-width:700px)').matches){rightPanel.dataset.mobileTab='sentence';mobileTabs.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.mobileTarget==='sentence'))}refreshQuoteEditor()}
  poster.addEventListener('click',event=>{const quote=event.target.closest('.quote');if(quote)selectQuote(quoteNodes().indexOf(quote));else{selectedQuoteIndex=-1;refreshQuoteEditor()}});
  function moveSelectedQuote(direction){const next=selectedQuoteIndex+direction;if(selectedQuoteIndex<0||next<0||next>=visibleQuoteLimit())return;pushHistory();const quotes=collections.custom.quotes;[quotes[selectedQuoteIndex],quotes[next]]=[quotes[next],quotes[selectedQuoteIndex]];const nodes=quoteNodes();const tone=nodes[selectedQuoteIndex].dataset.tone,scale=nodes[selectedQuoteIndex].dataset.scale,weight=nodes[selectedQuoteIndex].dataset.weight;nodes[selectedQuoteIndex].dataset.tone=nodes[next].dataset.tone||'';nodes[selectedQuoteIndex].dataset.scale=nodes[next].dataset.scale||'';nodes[selectedQuoteIndex].dataset.weight=nodes[next].dataset.weight||'';nodes[next].dataset.tone=tone||'';nodes[next].dataset.scale=scale||'';nodes[next].dataset.weight=weight||'';selectedQuoteIndex=next;setCollection('custom');refreshQuoteEditor();saveDraft()}
  document.querySelector('#moveQuoteUp').onclick=()=>moveSelectedQuote(-1);document.querySelector('#moveQuoteDown').onclick=()=>moveSelectedQuote(1);
  document.querySelector('#finishQuoteEdit').onclick=()=>{selectedQuoteIndex=-1;refreshQuoteEditor()};
  document.querySelectorAll('[data-quote-tone]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();const tone=button.dataset.quoteTone;if(tone==='default')delete quote.dataset.tone;else quote.dataset.tone=tone;refreshQuoteEditor();saveDraft()});
  document.querySelectorAll('[data-quote-scale]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();quote.dataset.scale=button.dataset.quoteScale;scheduleFit();refreshQuoteEditor();saveDraft()});
  document.querySelectorAll('[data-quote-weight]').forEach(button=>button.onclick=()=>{const quote=quoteNodes()[selectedQuoteIndex];if(!quote)return;pushHistory();const weight=button.dataset.quoteWeight;if(weight==='normal')delete quote.dataset.weight;else quote.dataset.weight=weight;scheduleFit();refreshQuoteEditor();saveDraft()});
  document.querySelector('#undoQuoteEdit').onclick=()=>{const draft=editHistory.pop();if(!draft)return;applyDraft(draft);document.querySelector('#undoQuoteEdit').disabled=editHistory.length===0;saveDraft()};
  document.querySelector('#resetQuoteEdits').onclick=()=>{if(activeCollection!=='custom')return;pushHistory();collections.custom.quotes=[...customDefaultQuotes];customLayouts={};poster.dataset.freeLayout='false';delete poster.dataset.freeLayoutPending;clearFreeLayoutStyles();quoteNodes().forEach(quote=>{delete quote.dataset.tone;delete quote.dataset.scale;delete quote.dataset.weight});selectedQuoteIndex=-1;setCollection('custom');refreshQuoteEditor();refreshFreeLayoutControls();saveDraft()};
