  const poster=document.querySelector('#poster');
  document.querySelector('#offset')?.closest('.section')?.remove();
  const collections={
    mao:{name:'毛泽东诗词摘录',meta:'9 条语录 · 阅读意象：跋涉',ghost:'路',seal:'跋<br>涉',quotes:['雄关漫道真如铁\n而今迈步从头越','红军不怕远征难，万水千山只等闲。','世上无难事，只要肯登攀。','为有牺牲多壮志，敢教日月换新天。','待到山花烂漫时，她在丛中笑。','数风流人物，还看今朝。','星星之火，可以燎原。','风物长宜放眼量。','自信人生二百年，会当水击三千里。']},
    sushi:{name:'苏轼词选',meta:'9 条语录 · 阅读意象：月与江',ghost:'月',seal:'江<br>月',quotes:['大江东去，浪淘尽，千古风流人物。','人生如梦，一尊还酹江月。','但愿人长久，千里共婵娟。','回首向来萧瑟处，归去，也无风雨也无晴。','竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。','拣尽寒枝不肯栖，寂寞沙洲冷。','相顾无言，惟有泪千行。','一点浩然气，千里快哉风。','人间有味是清欢。']},
    xin:{name:'辛弃疾词选',meta:'9 条语录 · 阅读意象：剑与长风',ghost:'剑',seal:'长<br>风',quotes:['醉里挑灯看剑，梦回吹角连营。','了却君王天下事，赢得生前身后名。','凭谁问：廉颇老矣，尚能饭否？','我见青山多妩媚，料青山见我应如是。','众里寻他千百度，蓦然回首，那人却在灯火阑珊处。','青山遮不住，毕竟东流去。','天下英雄谁敌手？曹刘。生子当如孙仲谋。','何处望神州？满眼风光北固楼。','最喜小儿无赖，溪头卧剥莲蓬。']}
  };
  const collectionSection=document.createElement('section');collectionSection.className='section';collectionSection.innerHTML='<div class="section-title">诗词版本</div><div class="choices"><button class="choice active" data-collection="mao">毛泽东诗词<span>跋涉、意志与开阔</span></button><button class="choice" data-collection="sushi">苏轼词选<span>江月、旷达与清欢</span></button><button class="choice" data-collection="xin">辛弃疾词选<span>剑与长风、壮志与苍凉</span></button></div>';document.querySelector('.right h2').after(collectionSection);
  const languageSection=document.createElement('section');languageSection.className='section';languageSection.innerHTML='<div class="section-title">字形</div><div class="choices density-choices"><button class="choice active" data-language="simplified">简体</button><button class="choice" data-language="traditional">繁體</button></div>';collectionSection.after(languageSection);
  const currentWorkSection=document.createElement('section');currentWorkSection.className='section';currentWorkSection.hidden=true;currentWorkSection.innerHTML='<div class="section-title">当前作品</div><div class="current-work"><span id="currentWorkName"></span><button id="reselectWork">重新选择诗词</button></div>';languageSection.before(currentWorkSection);
  const quoteEditSection=document.createElement('section');quoteEditSection.className='section';quoteEditSection.hidden=true;quoteEditSection.innerHTML='<div class="section-title">句子微调</div><div class="sentence-editor"><div class="selected-copy" id="selectedQuoteCopy">点击卡片中的一句诗</div><div class="micro-tools"><button id="moveQuoteUp" title="与上一句交换">↑</button><button id="moveQuoteDown" title="与下一句交换">↓</button><button id="finishQuoteEdit">完成</button><button id="undoQuoteEdit" disabled>撤销</button><button id="resetQuoteEdits">恢复默认</button></div><div class="free-layout-tools"><button id="toggleFreeLayout" type="button">开启自由调整</button><button id="resetFreeLayout" type="button" disabled>重置当前布局</button></div><div class="micro-tools" id="toneTools"><button data-quote-tone="white"><i class="tone-dot" style="background:#f2eee4"></i>白色</button><button data-quote-tone="lightgreen"><i class="tone-dot" style="background:#a9c7b1"></i>浅绿</button><button data-quote-tone="deepgreen"><i class="tone-dot" style="background:#34594b"></i>深绿</button><button data-quote-tone="lightgray"><i class="tone-dot" style="background:#b8b9b5"></i>浅灰</button><button data-quote-tone="black"><i class="tone-dot" style="background:#191b1b"></i>深黑</button></div><div class="micro-tools" id="weightTools"><button data-quote-weight="normal" class="active">常规</button><button data-quote-weight="bold">加粗</button></div><div class="micro-tools" id="sizeTools"><button data-quote-scale="0.86">紧凑</button><button data-quote-scale="1" class="active">标准</button><button data-quote-scale="1.16">强调</button></div><div class="sentence-help" id="sentenceHelp">默认使用安全网格。开启自由调整后，可拖拽句子；拖动右下角可放缩，系统会阻止越界和明显重叠。</div></div>';currentWorkSection.after(quoteEditSection);
  const formatSection=document.createElement('section');formatSection.className='section';formatSection.dataset.mobilePanel='layout';formatSection.innerHTML='<div class="section-title">画幅</div><div class="choices format-tools"><button class="choice active" data-format="social">3:4<span>社交分享</span></button><button class="choice" data-format="a4">A4<span>打印比例</span></button></div><div class="micro-tools" style="margin-top:8px"><button id="toggleSafeGuide">显示安全边距</button></div>';quoteEditSection.after(formatSection);
  const restoreLastButton=document.createElement('button');restoreLastButton.className='example';restoreLastButton.id='restoreLastWork';restoreLastButton.textContent='恢复上次作品';restoreLastButton.hidden=true;document.querySelector('.examples').appendChild(restoreLastButton);
  currentWorkSection.querySelector('#reselectWork').onclick=()=>{discovery.hidden=false;chooseView.hidden=true;searchView.hidden=false};
  document.querySelector('button[data-style="rupture"]')?.remove();
  const traditionalMap={'泽':'澤','东':'東','诗':'詩','词':'詞','录':'錄','条':'條','语':'語','阅':'閱','读':'讀','意':'意','象':'象','跋':'跋','涉':'涉','关':'關','漫':'漫','道':'道','真':'真','如':'如','铁':'鐵','迈':'邁','步':'步','头':'頭','红':'紅','军':'軍','远':'遠','征':'征','难':'難','万':'萬','千':'千','山':'山','闲':'閒','世':'世','无':'無','事':'事','只':'只','要':'要','肯':'肯','登':'登','攀':'攀','为':'為','牺':'犧','牲':'牲','多':'多','壮':'壯','志':'志','敢':'敢','教':'教','日':'日','月':'月','换':'換','新':'新','天':'天','时':'時','她':'她','丛':'叢','风':'風','流':'流','还':'還','今':'今','朝':'朝','星':'星','火':'火','可':'可','以':'以','燎':'燎','原':'原','物':'物','长':'長','宜':'宜','放':'放','眼':'眼','量':'量','自':'自','信':'信','百':'百','年':'年','会':'會','当':'當','水':'水','击':'擊','里':'裡','苏':'蘇','轼':'軾','选':'選','与':'與','江':'江','大':'大','去':'去','浪':'浪','淘':'淘','尽':'盡','古':'古','人':'人','梦':'夢','尊':'尊','酹':'酹','但':'但','愿':'願','久':'久','共':'共','婵':'嬋','娟':'娟','回':'回','首':'首','向':'向','来':'來','萧':'蕭','瑟':'瑟','处':'處','归':'歸','也':'也','雨':'雨','晴':'晴','竹':'竹','杖':'杖','芒':'芒','鞋':'鞋','轻':'輕','胜':'勝','马':'馬','谁':'誰','怕':'怕','蓑':'蓑','任':'任','平':'平','生':'生','拣':'揀','寒':'寒','枝':'枝','不':'不','栖':'棲','寂':'寂','寞':'寞','洲':'洲','冷':'冷','相':'相','顾':'顧','言':'言','惟':'惟','有':'有','泪':'淚','行':'行','点':'點','浩':'浩','然':'然','气':'氣','快':'快','哉':'哉','间':'間','味':'味','清':'清','欢':'歡','辛':'辛','弃':'棄','疾':'疾','剑':'劍','灯':'燈','看':'看','吹':'吹','角':'角','连':'連','营':'營','了':'了','却':'卻','君':'君','王':'王','下':'下','赢':'贏','得':'得','前':'前','后':'後','名':'名','凭':'憑','问':'問','颇':'頗','老':'老','矣':'矣','尚':'尚','能':'能','饭':'飯','否':'否','见':'見','青':'青','妩':'嫵','媚':'媚','料':'料','应':'應','是':'是','众':'眾','寻':'尋','他':'他','度':'度','蓦':'驀','那':'那','阑':'闌','珊':'珊','遮':'遮','毕':'畢','竟':'竟','英':'英','雄':'雄','敌':'敵','手':'手','曹':'曹','刘':'劉','孙':'孫','仲':'仲','谋':'謀','何':'何','望':'望','神':'神','州':'州','满':'滿','光':'光','北':'北','固':'固','楼':'樓','最':'最','喜':'喜','儿':'兒','赖':'賴','溪':'溪','卧':'臥','剥':'剝','莲':'蓮','蓬':'蓬','余':'餘','音':'音'};
  const toTraditional=text=>[...text].map(char=>traditionalMap[char]||char).join('');
  let activeCollection='mao',activeLanguage='simplified';
  const localize=text=>activeLanguage==='traditional'?toTraditional(text):text;
  function scheduleFit(){requestAnimationFrame(()=>requestAnimationFrame(fitQuotes))}
  function fitQuotes(){poster.querySelectorAll('.quote').forEach(quote=>{quote.style.removeProperty('font-size')});poster.querySelectorAll('.quote').forEach(quote=>{if(quote.offsetParent===null)return;let size=parseFloat(getComputedStyle(quote).fontSize)*Number(quote.dataset.scale||1);quote.style.setProperty('font-size',`${size}px`,'important');while((quote.scrollWidth>quote.clientWidth+1||quote.scrollHeight>quote.clientHeight+1)&&size>11){size-=1;quote.style.setProperty('font-size',`${size}px`,'important')}})}
  function applyQuoteLimit(){const item=collections[activeCollection];const limit=poster.dataset.style==='glyphfield'?9:7;poster.querySelectorAll('.quote').forEach((quote,index)=>{quote.hidden=index>=limit||!item.quotes[index]})}
  function setCollection(key){activeCollection=key;const item=collections[key];poster.querySelectorAll('.quote').forEach((quote,index)=>{const text=item.quotes[index];quote.hidden=!text;if(text)quote.innerHTML=localize(text).replace('\n','<br>');else quote.textContent=''});applyQuoteLimit();poster.querySelector('.ghost').textContent=localize(item.ghost);poster.querySelector('.seal').innerHTML=localize(item.seal);poster.querySelector('.edition').textContent=`${localize(item.name)} / ${localize('余音')} 2026`;document.querySelector('#sourceTitle').textContent=localize(item.name);document.querySelector('#sourceMeta').textContent=localize(item.meta);document.querySelector('.badge').textContent=localize(item.name);scheduleFit()}
  document.querySelectorAll('[data-collection]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-collection]').forEach(item=>item.classList.remove('active'));button.classList.add('active');setCollection(button.dataset.collection)});
  document.querySelectorAll('[data-language]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-language]').forEach(item=>item.classList.remove('active'));button.classList.add('active');activeLanguage=button.dataset.language;setCollection(activeCollection)});
  poster.dataset.density='balanced';
  const quoteTexts=['待到山花烂漫时，她在丛中笑。','数风流人物，还看今朝。','星星之火，可以燎原。','风物长宜放眼量。','自信人生二百年，会当水击三千里。'];
  poster.querySelector('.q5').textContent=quoteTexts[0];
  quoteTexts.slice(1).forEach((text,index)=>{const quote=document.createElement('div');quote.className=`quote q${index+6}`;quote.textContent=text;poster.querySelector('.edition').before(quote)});
  const quoteGrid=document.createElement('div');quoteGrid.className='quote-grid';poster.querySelectorAll('.quote').forEach(quote=>quoteGrid.appendChild(quote));poster.prepend(quoteGrid);
